### ISSUE TITLE
temp is always zero?

### ISSUE THREAD

**Issue by asantaga** [ivesdebruycker/maxcube#11]
Hi there, 

Just got some of these Max radiator valves and have some interesting uses for it. Ive looked at this API and noticed that 

a) the temp is always zero
b) valve status is always zero

is this a bug?

Angelo

**Comment by jwildeboer** [comment]
It's not really a bug. The thermostats only send updated temperature readings after a valve setting change. The usual workaround (which AFAICS has not yet been implemented here) is to change the valve setting a bit, read out the data again and set the valve value back to its original value. That's thoe only reliable way to get temperature data IIRC.

**Comment by ivesdebruycker** [comment]
@jwildeboer Yes, that was the workaround I was using, but because of reliability issues and the duty cycle limit I switched to separate temperature sensors.

It was implemented (see https://github.com/ivesdebruycker/maxcube/blob/84b3e15b9afaabb031f009442149120f3e69b9cf/maxcube.js#L62) but since has been removed.
