### ISSUE TITLE
Valves are set to Manual

### ISSUE THREAD

**Issue by jdr0berts** [ivesdebruycker/maxcube#6]
I've been using the maxcube package and have noticed that after a couple of minutes, each of the valves gets set to manual:
```
10/02/2015 22:38:02 ... "initialized":true,"fromCmd":false,"error":false,"valid":true,"mode":"AUTO" ...
10/02/2015 22:38:22 ... "initialized":true,"fromCmd":false,"error":false,"valid":true,"mode":"MANUAL" ...
10/02/2015 22:38:42 ... "initialized":true,"fromCmd":false,"error":false,"valid":true,"mode":"MANUAL" ...
```
I can't see anywhere that a command is sent to change the mode, is this something you've seen?

Thanks
James

**Comment by jdr0berts** [comment]
Having said that.... I can see a number of points where the devices are set to manual, I just need to work out why....

**Comment by ivesdebruycker** [comment]
To trigger the current (real) temperature to update, some setting needs to be changed in a thermostat. Every 15 minutes, the setpoint temperature is set, and then reset.
As you pointed out, this is in fact incorrect, it should be reset to same mode as before (auto, man, vacation).

Nevertheless, I found this set-reset-job to make the MAXcube unstable (not responding after a while), so maybe it should be made optional (if you're not interested in current temperature)

**Comment by Averelll** [comment]
I had exactly the same. Sometimes when the temperature is for example 19, the 15 minute interval job will not change from 19 to 19.5, but to 190.5 (or from 20 too 200.5) since this gets translated to a bit string, the result can be strange, setpoints set to 30, but also sometimes set to 9 degrees. I changed the code a bit from self.devicesStatus[rf_address].setpoint_user + 0.5 to (self.devicesStatus[rf_address].setpoint_user * 1) + 0.5. For me that did the trick (stable for a week now).

Averell
